-- Seed all countries and educational systems
-- 1. Curricula
INSERT INTO public.curricula (code, name, flag, curriculum_name) VALUES
('AF', 'Afghanistan', '🇦🇫', 'Afghanistan National Curriculum'),
('AX', 'Åland Islands', '🇦🇽', 'Åland Islands National Curriculum'),
('AL', 'Albania', '🇦🇱', 'Albania National Curriculum'),
('DZ', 'Algeria', '🇩🇿', 'Algeria National Curriculum'),
('AS', 'American Samoa', '🇦🇸', 'American Samoa National Curriculum'),
('AD', 'Andorra', '🇦🇩', 'Andorra National Curriculum'),
('AO', 'Angola', '🇦🇴', 'Angola National Curriculum'),
('AI', 'Anguilla', '🇦🇮', 'Anguilla National Curriculum'),
('AQ', 'Antarctica', '🇦🇶', 'Antarctica National Curriculum'),
('AG', 'Antigua and Barbuda', '🇦🇬', 'CSEC / CXC Curriculum'),
('AR', 'Argentina', '🇦🇷', 'Educación Secundaria'),
('AM', 'Armenia', '🇦🇲', 'Armenia National Curriculum'),
('AW', 'Aruba', '🇦🇼', 'Aruba National Curriculum'),
('AU', 'Australia', '🇦🇺', 'Australian Curriculum'),
('AT', 'Austria', '🇦🇹', 'Austria National Curriculum'),
('AZ', 'Azerbaijan', '🇦🇿', 'Azerbaijan National Curriculum'),
('BS', 'Bahamas', '🇧🇸', 'CSEC / CXC Curriculum'),
('BH', 'Bahrain', '🇧🇭', 'Bahrain National Curriculum'),
('BD', 'Bangladesh', '🇧🇩', 'NCTB Curriculum'),
('BB', 'Barbados', '🇧🇧', 'CSEC / CXC Curriculum'),
('BY', 'Belarus', '🇧🇾', 'Belarus National Curriculum'),
('BE', 'Belgium', '🇧🇪', 'Curriculum National'),
('BZ', 'Belize', '🇧🇿', 'CSEC / CXC Curriculum'),
('BJ', 'Benin', '🇧🇯', 'Curriculum National'),
('BM', 'Bermuda', '🇧🇲', 'Bermuda National Curriculum'),
('BT', 'Bhutan', '🇧🇹', 'Bhutan National Curriculum'),
('BO', 'Bolivia', '🇧🇴', 'Educación Secundaria'),
('BQ', 'Bonaire, Sint Eustatius and Saba', '🇧🇶', 'Bonaire, Sint Eustatius and Saba National Curriculum'),
('BA', 'Bosnia and Herzegovina', '🇧🇦', 'Bosnia and Herzegovina National Curriculum'),
('BW', 'Botswana', '🇧🇼', 'Botswana National Curriculum'),
('BV', 'Bouvet Island', '🇧🇻', 'Bouvet Island National Curriculum'),
('BR', 'Brazil', '🇧🇷', 'BNCC Curriculum'),
('IO', 'British Indian Ocean Territory', '🇮🇴', 'British Indian Ocean Territory National Curriculum'),
('BN', 'Brunei', '🇧🇳', 'Brunei National Curriculum'),
('BG', 'Bulgaria', '🇧🇬', 'Bulgaria National Curriculum'),
('BF', 'Burkina Faso', '🇧🇫', 'Curriculum National'),
('BI', 'Burundi', '🇧🇮', 'Curriculum National'),
('CV', 'Cabo Verde', '🇨🇻', 'Cabo Verde National Curriculum'),
('KH', 'Cambodia', '🇰🇭', 'Cambodia National Curriculum'),
('CM', 'Cameroon', '🇨🇲', 'Cameroon National Curriculum'),
('CA', 'Canada', '🇨🇦', 'Provincial Curriculum'),
('KY', 'Cayman Islands', '🇰🇾', 'Cayman Islands National Curriculum'),
('CF', 'Central African Republic', '🇨🇫', 'Curriculum National'),
('TD', 'Chad', '🇹🇩', 'Curriculum National'),
('CL', 'Chile', '🇨🇱', 'Educación Secundaria'),
('CN', 'China', '🇨🇳', 'National Curriculum'),
('CX', 'Christmas Island', '🇨🇽', 'Christmas Island National Curriculum'),
('CC', 'Cocos (Keeling) Islands', '🇨🇨', 'Cocos (Keeling) Islands National Curriculum'),
('CO', 'Colombia', '🇨🇴', 'Educación Secundaria'),
('KM', 'Comoros', '🇰🇲', 'Curriculum National'),
('CD', 'Congo (DRC)', '🇨🇩', 'Curriculum National'),
('CG', 'Congo', '🇨🇬', 'Curriculum National'),
('CK', 'Cook Islands', '🇨🇰', 'Cook Islands National Curriculum'),
('CR', 'Costa Rica', '🇨🇷', 'Educación Secundaria'),
('CI', 'Côte d''Ivoire', '🇨🇮', 'Curriculum National'),
('HR', 'Croatia', '🇭🇷', 'Croatia National Curriculum'),
('CU', 'Cuba', '🇨🇺', 'Educación Secundaria'),
('CW', 'Curaçao', '🇨🇼', 'Curaçao National Curriculum'),
('CY', 'Cyprus', '🇨🇾', 'Cyprus National Curriculum'),
('CZ', 'Czechia', '🇨🇿', 'Czechia National Curriculum'),
('DK', 'Denmark', '🇩🇰', 'Denmark National Curriculum'),
('DJ', 'Djibouti', '🇩🇯', 'Curriculum National'),
('DM', 'Dominica', '🇩🇲', 'CSEC / CXC Curriculum'),
('DO', 'Dominican Republic', '🇩🇴', 'Educación Secundaria'),
('EC', 'Ecuador', '🇪🇨', 'Educación Secundaria'),
('EG', 'Egypt', '🇪🇬', 'Egypt National Curriculum'),
('SV', 'El Salvador', '🇸🇻', 'Educación Secundaria'),
('GQ', 'Equatorial Guinea', '🇬🇶', 'Educación Secundaria'),
('ER', 'Eritrea', '🇪🇷', 'Eritrea National Curriculum'),
('EE', 'Estonia', '🇪🇪', 'Estonia National Curriculum'),
('SZ', 'Eswatini', '🇸🇿', 'Eswatini National Curriculum'),
('ET', 'Ethiopia', '🇪🇹', 'Ethiopia National Curriculum'),
('FK', 'Falkland Islands', '🇫🇰', 'Falkland Islands National Curriculum'),
('FO', 'Faroe Islands', '🇫🇴', 'Faroe Islands National Curriculum'),
('FJ', 'Fiji', '🇫🇯', 'Fiji National Curriculum'),
('FI', 'Finland', '🇫🇮', 'Finland National Curriculum'),
('FR', 'France', '🇫🇷', 'French National Curriculum'),
('GF', 'French Guiana', '🇬🇫', 'French Guiana National Curriculum'),
('PF', 'French Polynesia', '🇵🇫', 'French Polynesia National Curriculum'),
('TF', 'French Southern Territories', '🇹🇫', 'French Southern Territories National Curriculum'),
('GA', 'Gabon', '🇬🇦', 'Curriculum National'),
('GM', 'Gambia', '🇬🇲', 'Gambia National Curriculum'),
('GE', 'Georgia', '🇬🇪', 'Georgia National Curriculum'),
('DE', 'Germany', '🇩🇪', 'Abitur / Gymnasium'),
('GH', 'Ghana', '🇬🇭', 'GES / WAEC'),
('GI', 'Gibraltar', '🇬🇮', 'Gibraltar National Curriculum'),
('GR', 'Greece', '🇬🇷', 'Greece National Curriculum'),
('GL', 'Greenland', '🇬🇱', 'Greenland National Curriculum'),
('GD', 'Grenada', '🇬🇩', 'CSEC / CXC Curriculum'),
('GP', 'Guadeloupe', '🇬🇵', 'Guadeloupe National Curriculum'),
('GU', 'Guam', '🇬🇺', 'Guam National Curriculum'),
('GT', 'Guatemala', '🇬🇹', 'Educación Secundaria'),
('GG', 'Guernsey', '🇬🇬', 'Guernsey National Curriculum'),
('GN', 'Guinea', '🇬🇳', 'Curriculum National'),
('GW', 'Guinea-Bissau', '🇬🇼', 'Guinea-Bissau National Curriculum'),
('GY', 'Guyana', '🇬🇾', 'CSEC / CXC Curriculum'),
('HT', 'Haiti', '🇭🇹', 'Curriculum National'),
('HM', 'Heard Island and McDonald Islands', '🇭🇲', 'Heard Island and McDonald Islands National Curriculum'),
('VA', 'Holy See', '🇻🇦', 'Holy See National Curriculum'),
('HN', 'Honduras', '🇭🇳', 'Educación Secundaria'),
('HK', 'Hong Kong', '🇭🇰', 'Hong Kong National Curriculum'),
('HU', 'Hungary', '🇭🇺', 'Hungary National Curriculum'),
('IS', 'Iceland', '🇮🇸', 'Iceland National Curriculum'),
('IN', 'India', '🇮🇳', 'CBSE / ICSE'),
('ID', 'Indonesia', '🇮🇩', 'Indonesia National Curriculum'),
('IR', 'Iran', '🇮🇷', 'Iran National Curriculum'),
('IQ', 'Iraq', '🇮🇶', 'Iraq National Curriculum'),
('IE', 'Ireland', '🇮🇪', 'Ireland National Curriculum'),
('IM', 'Isle of Man', '🇮🇲', 'Isle of Man National Curriculum'),
('IL', 'Israel', '🇮🇱', 'Israel National Curriculum'),
('IT', 'Italy', '🇮🇹', 'Italy National Curriculum'),
('JM', 'Jamaica', '🇯🇲', 'Jamaica National Curriculum'),
('JP', 'Japan', '🇯🇵', 'MEXT Curriculum'),
('JE', 'Jersey', '🇯🇪', 'Jersey National Curriculum'),
('JO', 'Jordan', '🇯🇴', 'Jordan National Curriculum'),
('KZ', 'Kazakhstan', '🇰🇿', 'Kazakhstan National Curriculum'),
('KE', 'Kenya', '🇰🇪', 'CBC Curriculum'),
('KI', 'Kiribati', '🇰🇮', 'Kiribati National Curriculum'),
('KP', 'North Korea', '🇰🇵', 'North Korea National Curriculum'),
('KR', 'South Korea', '🇰🇷', 'South Korea National Curriculum'),
('KW', 'Kuwait', '🇰🇼', 'Kuwait National Curriculum'),
('KG', 'Kyrgyzstan', '🇰🇬', 'Kyrgyzstan National Curriculum'),
('LA', 'Laos', '🇱🇦', 'Laos National Curriculum'),
('LV', 'Latvia', '🇱🇻', 'Latvia National Curriculum'),
('LB', 'Lebanon', '🇱🇧', 'Lebanon National Curriculum'),
('LS', 'Lesotho', '🇱🇸', 'Lesotho National Curriculum'),
('LR', 'Liberia', '🇱🇷', 'Liberia National Curriculum'),
('LY', 'Libya', '🇱🇾', 'Libya National Curriculum'),
('LI', 'Liechtenstein', '🇱🇮', 'Liechtenstein National Curriculum'),
('LT', 'Lithuania', '🇱🇹', 'Lithuania National Curriculum'),
('LU', 'Luxembourg', '🇱🇺', 'Luxembourg National Curriculum'),
('MO', 'Macao', '🇲🇴', 'Macao National Curriculum'),
('MG', 'Madagascar', '🇲🇬', 'Curriculum National'),
('MW', 'Malawi', '🇲🇼', 'Malawi National Curriculum'),
('MY', 'Malaysia', '🇲🇾', 'Malaysia National Curriculum'),
('MV', 'Maldives', '🇲🇻', 'Maldives National Curriculum'),
('ML', 'Mali', '🇲🇱', 'Curriculum National'),
('MT', 'Malta', '🇲🇹', 'Malta National Curriculum'),
('MH', 'Marshall Islands', '🇲🇭', 'Marshall Islands National Curriculum'),
('MQ', 'Martinique', '🇲🇶', 'Martinique National Curriculum'),
('MR', 'Mauritania', '🇲🇷', 'Mauritania National Curriculum'),
('MU', 'Mauritius', '🇲🇺', 'Mauritius National Curriculum'),
('YT', 'Mayotte', '🇾🇹', 'Mayotte National Curriculum'),
('MX', 'Mexico', '🇲🇽', 'SEP Curriculum'),
('FM', 'Micronesia', '🇫🇲', 'Micronesia National Curriculum'),
('MD', 'Moldova', '🇲🇩', 'Moldova National Curriculum'),
('MC', 'Monaco', '🇲🇨', 'Curriculum National'),
('MN', 'Mongolia', '🇲🇳', 'Mongolia National Curriculum'),
('ME', 'Montenegro', '🇲🇪', 'Montenegro National Curriculum'),
('MS', 'Montserrat', '🇲🇸', 'Montserrat National Curriculum'),
('MA', 'Morocco', '🇲🇦', 'Morocco National Curriculum'),
('MZ', 'Mozambique', '🇲🇿', 'Mozambique National Curriculum'),
('MM', 'Myanmar', '🇲🇲', 'Myanmar National Curriculum'),
('NA', 'Namibia', '🇳🇦', 'Namibia National Curriculum'),
('NR', 'Nauru', '🇳🇷', 'Nauru National Curriculum'),
('NP', 'Nepal', '🇳🇵', 'Nepal National Curriculum'),
('NL', 'Netherlands', '🇳🇱', 'Netherlands National Curriculum'),
('NC', 'New Caledonia', '🇳🇨', 'New Caledonia National Curriculum'),
('NZ', 'New Zealand', '🇳🇿', 'NCEA Curriculum'),
('NI', 'Nicaragua', '🇳🇮', 'Educación Secundaria'),
('NE', 'Niger', '🇳🇪', 'Curriculum National'),
('NG', 'Nigeria', '🇳🇬', 'NERDC / WAEC'),
('NU', 'Niue', '🇳🇺', 'Niue National Curriculum'),
('NF', 'Norfolk Island', '🇳🇫', 'Norfolk Island National Curriculum'),
('MP', 'Northern Mariana Islands', '🇲🇵', 'Northern Mariana Islands National Curriculum'),
('NO', 'Norway', '🇳🇴', 'Norway National Curriculum'),
('OM', 'Oman', '🇴🇲', 'Oman National Curriculum'),
('PK', 'Pakistan', '🇵🇰', 'National Curriculum'),
('PW', 'Palau', '🇵🇼', 'Palau National Curriculum'),
('PS', 'Palestine', '🇵🇸', 'Palestine National Curriculum'),
('PA', 'Panama', '🇵🇦', 'Educación Secundaria'),
('PG', 'Papua New Guinea', '🇵🇬', 'Papua New Guinea National Curriculum'),
('PY', 'Paraguay', '🇵🇾', 'Educación Secundaria'),
('PE', 'Peru', '🇵🇪', 'Educación Secundaria'),
('PH', 'Philippines', '🇵🇭', 'Philippines National Curriculum'),
('PN', 'Pitcairn', '🇵🇳', 'Pitcairn National Curriculum'),
('PL', 'Poland', '🇵🇱', 'Poland National Curriculum'),
('PT', 'Portugal', '🇵🇹', 'Portugal National Curriculum'),
('PR', 'Puerto Rico', '🇵🇷', 'Puerto Rico National Curriculum'),
('QA', 'Qatar', '🇶🇦', 'Qatar National Curriculum'),
('RE', 'Réunion', '🇷🇪', 'Réunion National Curriculum'),
('RO', 'Romania', '🇷🇴', 'Romania National Curriculum'),
('RU', 'Russia', '🇷🇺', 'Russia National Curriculum'),
('RW', 'Rwanda', '🇷🇼', 'Curriculum National'),
('BL', 'Saint Barthélemy', '🇧🇱', 'Saint Barthélemy National Curriculum'),
('SH', 'Saint Helena', '🇸🇭', 'Saint Helena National Curriculum'),
('KN', 'Saint Kitts and Nevis', '🇰🇳', 'CSEC / CXC Curriculum'),
('LC', 'Saint Lucia', '🇱🇨', 'CSEC / CXC Curriculum'),
('MF', 'Saint Martin', '🇲🇫', 'Saint Martin National Curriculum'),
('PM', 'Saint Pierre and Miquelon', '🇵🇲', 'Saint Pierre and Miquelon National Curriculum'),
('VC', 'Saint Vincent and the Grenadines', '🇻🇨', 'CSEC / CXC Curriculum'),
('WS', 'Samoa', '🇼🇸', 'Samoa National Curriculum'),
('SM', 'San Marino', '🇸🇲', 'San Marino National Curriculum'),
('ST', 'São Tomé and Príncipe', '🇸🇹', 'São Tomé and Príncipe National Curriculum'),
('SA', 'Saudi Arabia', '🇸🇦', 'Saudi Arabia National Curriculum'),
('SN', 'Senegal', '🇸🇳', 'Curriculum National'),
('RS', 'Serbia', '🇷🇸', 'Serbia National Curriculum'),
('SC', 'Seychelles', '🇸🇨', 'Seychelles National Curriculum'),
('SL', 'Sierra Leone', '🇸🇱', 'Sierra Leone National Curriculum'),
('SG', 'Singapore', '🇸🇬', 'GCE O-Level / MOE'),
('SX', 'Sint Maarten', '🇸🇽', 'Sint Maarten National Curriculum'),
('SK', 'Slovakia', '🇸🇰', 'Slovakia National Curriculum'),
('SI', 'Slovenia', '🇸🇮', 'Slovenia National Curriculum'),
('SB', 'Solomon Islands', '🇸🇧', 'Solomon Islands National Curriculum'),
('SO', 'Somalia', '🇸🇴', 'Somalia National Curriculum'),
('ZA', 'South Africa', '🇿🇦', 'CAPS Curriculum'),
('GS', 'South Georgia and the South Sandwich Islands', '🇬🇸', 'South Georgia and the South Sandwich Islands National Curriculum'),
('SS', 'South Sudan', '🇸🇸', 'South Sudan National Curriculum'),
('ES', 'Spain', '🇪🇸', 'LOMLOE / Bachillerato'),
('LK', 'Sri Lanka', '🇱🇰', 'Sri Lanka National Curriculum'),
('SD', 'Sudan', '🇸🇩', 'Sudan National Curriculum'),
('SR', 'Suriname', '🇸🇷', 'Suriname National Curriculum'),
('SJ', 'Svalbard and Jan Mayen', '🇸🇯', 'Svalbard and Jan Mayen National Curriculum'),
('SE', 'Sweden', '🇸🇪', 'Sweden National Curriculum'),
('CH', 'Switzerland', '🇨🇭', 'Switzerland National Curriculum'),
('SY', 'Syria', '🇸🇾', 'Syria National Curriculum'),
('TW', 'Taiwan', '🇹🇼', 'Taiwan National Curriculum'),
('TJ', 'Tajikistan', '🇹🇯', 'Tajikistan National Curriculum'),
('TZ', 'Tanzania', '🇹🇿', 'Tanzania National Curriculum'),
('TH', 'Thailand', '🇹🇭', 'Thailand National Curriculum'),
('TL', 'Timor-Leste', '🇹🇱', 'Timor-Leste National Curriculum'),
('TG', 'Togo', '🇹🇬', 'Curriculum National'),
('TK', 'Tokelau', '🇹🇰', 'Tokelau National Curriculum'),
('TO', 'Tonga', '🇹🇴', 'Tonga National Curriculum'),
('TT', 'Trinidad and Tobago', '🇹🇹', 'CSEC / CXC Curriculum'),
('TN', 'Tunisia', '🇹🇳', 'Curriculum National'),
('TR', 'Turkey', '🇹🇷', 'Turkey National Curriculum'),
('TM', 'Turkmenistan', '🇹🇲', 'Turkmenistan National Curriculum'),
('TC', 'Turks and Caicos Islands', '🇹🇨', 'Turks and Caicos Islands National Curriculum'),
('TV', 'Tuvalu', '🇹🇻', 'Tuvalu National Curriculum'),
('UG', 'Uganda', '🇺🇬', 'Uganda National Curriculum'),
('UA', 'Ukraine', '🇺🇦', 'Ukraine National Curriculum'),
('AE', 'United Arab Emirates', '🇦🇪', 'United Arab Emirates National Curriculum'),
('GB', 'United Kingdom', '🇬🇧', 'GCSE'),
('UM', 'United States Minor Outlying Islands', '🇺🇲', 'United States Minor Outlying Islands National Curriculum'),
('US', 'United States', '🇺🇸', 'Common Core'),
('UY', 'Uruguay', '🇺🇾', 'Educación Secundaria'),
('UZ', 'Uzbekistan', '🇺🇿', 'Uzbekistan National Curriculum'),
('VU', 'Vanuatu', '🇻🇺', 'Curriculum National'),
('VE', 'Venezuela', '🇻🇪', 'Educación Secundaria'),
('VN', 'Vietnam', '🇻🇳', 'Vietnam National Curriculum'),
('VG', 'British Virgin Islands', '🇻🇬', 'British Virgin Islands National Curriculum'),
('VI', 'U.S. Virgin Islands', '🇻🇮', 'U.S. Virgin Islands National Curriculum'),
('WF', 'Wallis and Futuna', '🇼🇫', 'Wallis and Futuna National Curriculum'),
('EH', 'Western Sahara', '🇪🇭', 'Western Sahara National Curriculum'),
('YE', 'Yemen', '🇾🇪', 'Yemen National Curriculum'),
('ZM', 'Zambia', '🇿🇲', 'Zambia National Curriculum'),
('ZW', 'Zimbabwe', '🇿🇼', 'Zimbabwe National Curriculum')
ON CONFLICT (code) DO UPDATE SET
  name = EXCLUDED.name,
  flag = EXCLUDED.flag,
  curriculum_name = EXCLUDED.curriculum_name;

-- 2. Grades
INSERT INTO public.grades (id, country_code, label) VALUES
('af-g7', 'AF', 'Grade 7'),
('af-g8', 'AF', 'Grade 8'),
('af-g9', 'AF', 'Grade 9'),
('af-g10', 'AF', 'Grade 10'),
('ax-g7', 'AX', 'Grade 7'),
('ax-g8', 'AX', 'Grade 8'),
('ax-g9', 'AX', 'Grade 9'),
('ax-g10', 'AX', 'Grade 10'),
('al-g7', 'AL', 'Grade 7'),
('al-g8', 'AL', 'Grade 8'),
('al-g9', 'AL', 'Grade 9'),
('al-g10', 'AL', 'Grade 10'),
('dz-g7', 'DZ', 'Grade 7'),
('dz-g8', 'DZ', 'Grade 8'),
('dz-g9', 'DZ', 'Grade 9'),
('dz-g10', 'DZ', 'Grade 10'),
('as-g7', 'AS', 'Grade 7'),
('as-g8', 'AS', 'Grade 8'),
('as-g9', 'AS', 'Grade 9'),
('as-g10', 'AS', 'Grade 10'),
('ad-g7', 'AD', 'Grade 7'),
('ad-g8', 'AD', 'Grade 8'),
('ad-g9', 'AD', 'Grade 9'),
('ad-g10', 'AD', 'Grade 10'),
('ao-g7', 'AO', 'Grade 7'),
('ao-g8', 'AO', 'Grade 8'),
('ao-g9', 'AO', 'Grade 9'),
('ao-g10', 'AO', 'Grade 10'),
('ai-g7', 'AI', 'Grade 7'),
('ai-g8', 'AI', 'Grade 8'),
('ai-g9', 'AI', 'Grade 9'),
('ai-g10', 'AI', 'Grade 10'),
('aq-g7', 'AQ', 'Grade 7'),
('aq-g8', 'AQ', 'Grade 8'),
('aq-g9', 'AQ', 'Grade 9'),
('aq-g10', 'AQ', 'Grade 10'),
('ag-f1', 'AG', 'Form 1'),
('ag-f2', 'AG', 'Form 2'),
('ag-f3', 'AG', 'Form 3'),
('ar-g7', 'AR', '7º Grado'),
('ar-g8', 'AR', '8º Grado'),
('ar-g9', 'AR', '9º Grado'),
('am-g7', 'AM', 'Grade 7'),
('am-g8', 'AM', 'Grade 8'),
('am-g9', 'AM', 'Grade 9'),
('am-g10', 'AM', 'Grade 10'),
('aw-g7', 'AW', 'Grade 7'),
('aw-g8', 'AW', 'Grade 8'),
('aw-g9', 'AW', 'Grade 9'),
('aw-g10', 'AW', 'Grade 10'),
('au-y7', 'AU', 'Year 7'),
('au-y8', 'AU', 'Year 8'),
('au-y9', 'AU', 'Year 9'),
('au-y10', 'AU', 'Year 10'),
('at-g7', 'AT', 'Grade 7'),
('at-g8', 'AT', 'Grade 8'),
('at-g9', 'AT', 'Grade 9'),
('at-g10', 'AT', 'Grade 10'),
('az-g7', 'AZ', 'Grade 7'),
('az-g8', 'AZ', 'Grade 8'),
('az-g9', 'AZ', 'Grade 9'),
('az-g10', 'AZ', 'Grade 10'),
('bs-f1', 'BS', 'Form 1'),
('bs-f2', 'BS', 'Form 2'),
('bs-f3', 'BS', 'Form 3'),
('bh-g7', 'BH', 'Grade 7'),
('bh-g8', 'BH', 'Grade 8'),
('bh-g9', 'BH', 'Grade 9'),
('bh-g10', 'BH', 'Grade 10'),
('bd-c7', 'BD', 'Class 7'),
('bd-c8', 'BD', 'Class 8'),
('bd-c9', 'BD', 'Class 9'),
('bd-c10', 'BD', 'Class 10'),
('bb-f1', 'BB', 'Form 1'),
('bb-f2', 'BB', 'Form 2'),
('bb-f3', 'BB', 'Form 3'),
('by-g7', 'BY', 'Grade 7'),
('by-g8', 'BY', 'Grade 8'),
('by-g9', 'BY', 'Grade 9'),
('by-g10', 'BY', 'Grade 10'),
('be-g6', 'BE', '6ème'),
('be-g5', 'BE', '5ème'),
('be-g4', 'BE', '4ème'),
('be-g3', 'BE', '3ème'),
('bz-f1', 'BZ', 'Form 1'),
('bz-f2', 'BZ', 'Form 2'),
('bz-f3', 'BZ', 'Form 3'),
('bj-g6', 'BJ', '6ème'),
('bj-g5', 'BJ', '5ème'),
('bj-g4', 'BJ', '4ème'),
('bj-g3', 'BJ', '3ème'),
('bm-g7', 'BM', 'Grade 7'),
('bm-g8', 'BM', 'Grade 8'),
('bm-g9', 'BM', 'Grade 9'),
('bm-g10', 'BM', 'Grade 10'),
('bt-g7', 'BT', 'Grade 7'),
('bt-g8', 'BT', 'Grade 8'),
('bt-g9', 'BT', 'Grade 9'),
('bt-g10', 'BT', 'Grade 10'),
('bo-g7', 'BO', '7º Grado'),
('bo-g8', 'BO', '8º Grado'),
('bo-g9', 'BO', '9º Grado'),
('bq-g7', 'BQ', 'Grade 7'),
('bq-g8', 'BQ', 'Grade 8'),
('bq-g9', 'BQ', 'Grade 9'),
('bq-g10', 'BQ', 'Grade 10'),
('ba-g7', 'BA', 'Grade 7'),
('ba-g8', 'BA', 'Grade 8'),
('ba-g9', 'BA', 'Grade 9'),
('ba-g10', 'BA', 'Grade 10'),
('bw-g7', 'BW', 'Grade 7'),
('bw-g8', 'BW', 'Grade 8'),
('bw-g9', 'BW', 'Grade 9'),
('bw-g10', 'BW', 'Grade 10'),
('bv-g7', 'BV', 'Grade 7'),
('bv-g8', 'BV', 'Grade 8'),
('bv-g9', 'BV', 'Grade 9'),
('bv-g10', 'BV', 'Grade 10'),
('br-a7', 'BR', '7º Ano'),
('br-a8', 'BR', '8º Ano'),
('br-a9', 'BR', '9º Ano'),
('io-g7', 'IO', 'Grade 7'),
('io-g8', 'IO', 'Grade 8'),
('io-g9', 'IO', 'Grade 9'),
('io-g10', 'IO', 'Grade 10'),
('bn-g7', 'BN', 'Grade 7'),
('bn-g8', 'BN', 'Grade 8'),
('bn-g9', 'BN', 'Grade 9'),
('bn-g10', 'BN', 'Grade 10'),
('bg-g7', 'BG', 'Grade 7'),
('bg-g8', 'BG', 'Grade 8'),
('bg-g9', 'BG', 'Grade 9'),
('bg-g10', 'BG', 'Grade 10'),
('bf-g6', 'BF', '6ème'),
('bf-g5', 'BF', '5ème'),
('bf-g4', 'BF', '4ème'),
('bf-g3', 'BF', '3ème'),
('bi-g6', 'BI', '6ème'),
('bi-g5', 'BI', '5ème'),
('bi-g4', 'BI', '4ème'),
('bi-g3', 'BI', '3ème'),
('cv-g7', 'CV', 'Grade 7'),
('cv-g8', 'CV', 'Grade 8'),
('cv-g9', 'CV', 'Grade 9'),
('cv-g10', 'CV', 'Grade 10'),
('kh-g7', 'KH', 'Grade 7'),
('kh-g8', 'KH', 'Grade 8'),
('kh-g9', 'KH', 'Grade 9'),
('kh-g10', 'KH', 'Grade 10'),
('cm-g7', 'CM', 'Grade 7'),
('cm-g8', 'CM', 'Grade 8'),
('cm-g9', 'CM', 'Grade 9'),
('cm-g10', 'CM', 'Grade 10'),
('ca-g7', 'CA', 'Grade 7'),
('ca-g8', 'CA', 'Grade 8'),
('ca-g9', 'CA', 'Grade 9'),
('ca-g10', 'CA', 'Grade 10'),
('ky-g7', 'KY', 'Grade 7'),
('ky-g8', 'KY', 'Grade 8'),
('ky-g9', 'KY', 'Grade 9'),
('ky-g10', 'KY', 'Grade 10'),
('cf-g6', 'CF', '6ème'),
('cf-g5', 'CF', '5ème'),
('cf-g4', 'CF', '4ème'),
('cf-g3', 'CF', '3ème'),
('td-g6', 'TD', '6ème'),
('td-g5', 'TD', '5ème'),
('td-g4', 'TD', '4ème'),
('td-g3', 'TD', '3ème'),
('cl-g7', 'CL', '7º Grado'),
('cl-g8', 'CL', '8º Grado'),
('cl-g9', 'CL', '9º Grado'),
('cn-g7', 'CN', 'Grade 7'),
('cn-g8', 'CN', 'Grade 8'),
('cn-g9', 'CN', 'Grade 9'),
('cx-g7', 'CX', 'Grade 7'),
('cx-g8', 'CX', 'Grade 8'),
('cx-g9', 'CX', 'Grade 9'),
('cx-g10', 'CX', 'Grade 10'),
('cc-g7', 'CC', 'Grade 7'),
('cc-g8', 'CC', 'Grade 8'),
('cc-g9', 'CC', 'Grade 9'),
('cc-g10', 'CC', 'Grade 10'),
('co-g7', 'CO', '7º Grado'),
('co-g8', 'CO', '8º Grado'),
('co-g9', 'CO', '9º Grado'),
('km-g6', 'KM', '6ème'),
('km-g5', 'KM', '5ème'),
('km-g4', 'KM', '4ème'),
('km-g3', 'KM', '3ème'),
('cd-g6', 'CD', '6ème'),
('cd-g5', 'CD', '5ème'),
('cd-g4', 'CD', '4ème'),
('cd-g3', 'CD', '3ème'),
('cg-g6', 'CG', '6ème'),
('cg-g5', 'CG', '5ème'),
('cg-g4', 'CG', '4ème'),
('cg-g3', 'CG', '3ème'),
('ck-g7', 'CK', 'Grade 7'),
('ck-g8', 'CK', 'Grade 8'),
('ck-g9', 'CK', 'Grade 9'),
('ck-g10', 'CK', 'Grade 10'),
('cr-g7', 'CR', '7º Grado'),
('cr-g8', 'CR', '8º Grado'),
('cr-g9', 'CR', '9º Grado'),
('ci-g6', 'CI', '6ème'),
('ci-g5', 'CI', '5ème'),
('ci-g4', 'CI', '4ème'),
('ci-g3', 'CI', '3ème'),
('hr-g7', 'HR', 'Grade 7'),
('hr-g8', 'HR', 'Grade 8'),
('hr-g9', 'HR', 'Grade 9'),
('hr-g10', 'HR', 'Grade 10'),
('cu-g7', 'CU', '7º Grado'),
('cu-g8', 'CU', '8º Grado'),
('cu-g9', 'CU', '9º Grado'),
('cw-g7', 'CW', 'Grade 7'),
('cw-g8', 'CW', 'Grade 8'),
('cw-g9', 'CW', 'Grade 9'),
('cw-g10', 'CW', 'Grade 10'),
('cy-g7', 'CY', 'Grade 7'),
('cy-g8', 'CY', 'Grade 8'),
('cy-g9', 'CY', 'Grade 9'),
('cy-g10', 'CY', 'Grade 10'),
('cz-g7', 'CZ', 'Grade 7'),
('cz-g8', 'CZ', 'Grade 8'),
('cz-g9', 'CZ', 'Grade 9'),
('cz-g10', 'CZ', 'Grade 10'),
('dk-g7', 'DK', 'Grade 7'),
('dk-g8', 'DK', 'Grade 8'),
('dk-g9', 'DK', 'Grade 9'),
('dk-g10', 'DK', 'Grade 10'),
('dj-g6', 'DJ', '6ème'),
('dj-g5', 'DJ', '5ème'),
('dj-g4', 'DJ', '4ème'),
('dj-g3', 'DJ', '3ème'),
('dm-f1', 'DM', 'Form 1'),
('dm-f2', 'DM', 'Form 2'),
('dm-f3', 'DM', 'Form 3'),
('do-g7', 'DO', '7º Grado'),
('do-g8', 'DO', '8º Grado'),
('do-g9', 'DO', '9º Grado'),
('ec-g7', 'EC', '7º Grado'),
('ec-g8', 'EC', '8º Grado'),
('ec-g9', 'EC', '9º Grado'),
('eg-g7', 'EG', 'Grade 7'),
('eg-g8', 'EG', 'Grade 8'),
('eg-g9', 'EG', 'Grade 9'),
('eg-g10', 'EG', 'Grade 10'),
('sv-g7', 'SV', '7º Grado'),
('sv-g8', 'SV', '8º Grado'),
('sv-g9', 'SV', '9º Grado'),
('gq-g7', 'GQ', '7º Grado'),
('gq-g8', 'GQ', '8º Grado'),
('gq-g9', 'GQ', '9º Grado'),
('er-g7', 'ER', 'Grade 7'),
('er-g8', 'ER', 'Grade 8'),
('er-g9', 'ER', 'Grade 9'),
('er-g10', 'ER', 'Grade 10'),
('ee-g7', 'EE', 'Grade 7'),
('ee-g8', 'EE', 'Grade 8'),
('ee-g9', 'EE', 'Grade 9'),
('ee-g10', 'EE', 'Grade 10'),
('sz-g7', 'SZ', 'Grade 7'),
('sz-g8', 'SZ', 'Grade 8'),
('sz-g9', 'SZ', 'Grade 9'),
('sz-g10', 'SZ', 'Grade 10'),
('et-g7', 'ET', 'Grade 7'),
('et-g8', 'ET', 'Grade 8'),
('et-g9', 'ET', 'Grade 9'),
('et-g10', 'ET', 'Grade 10'),
('fk-g7', 'FK', 'Grade 7'),
('fk-g8', 'FK', 'Grade 8'),
('fk-g9', 'FK', 'Grade 9'),
('fk-g10', 'FK', 'Grade 10'),
('fo-g7', 'FO', 'Grade 7'),
('fo-g8', 'FO', 'Grade 8'),
('fo-g9', 'FO', 'Grade 9'),
('fo-g10', 'FO', 'Grade 10'),
('fj-g7', 'FJ', 'Grade 7'),
('fj-g8', 'FJ', 'Grade 8'),
('fj-g9', 'FJ', 'Grade 9'),
('fj-g10', 'FJ', 'Grade 10'),
('fi-g7', 'FI', 'Grade 7'),
('fi-g8', 'FI', 'Grade 8'),
('fi-g9', 'FI', 'Grade 9'),
('fi-g10', 'FI', 'Grade 10'),
('fr-6eme', 'FR', '6ème'),
('fr-5eme', 'FR', '5ème'),
('fr-4eme', 'FR', '4ème'),
('fr-3eme', 'FR', '3ème'),
('gf-g7', 'GF', 'Grade 7'),
('gf-g8', 'GF', 'Grade 8'),
('gf-g9', 'GF', 'Grade 9'),
('gf-g10', 'GF', 'Grade 10'),
('pf-g7', 'PF', 'Grade 7'),
('pf-g8', 'PF', 'Grade 8'),
('pf-g9', 'PF', 'Grade 9'),
('pf-g10', 'PF', 'Grade 10'),
('tf-g7', 'TF', 'Grade 7'),
('tf-g8', 'TF', 'Grade 8'),
('tf-g9', 'TF', 'Grade 9'),
('tf-g10', 'TF', 'Grade 10'),
('ga-g6', 'GA', '6ème'),
('ga-g5', 'GA', '5ème'),
('ga-g4', 'GA', '4ème'),
('ga-g3', 'GA', '3ème'),
('gm-g7', 'GM', 'Grade 7'),
('gm-g8', 'GM', 'Grade 8'),
('gm-g9', 'GM', 'Grade 9'),
('gm-g10', 'GM', 'Grade 10'),
('ge-g7', 'GE', 'Grade 7'),
('ge-g8', 'GE', 'Grade 8'),
('ge-g9', 'GE', 'Grade 9'),
('ge-g10', 'GE', 'Grade 10'),
('de-k7', 'DE', 'Klasse 7'),
('de-k8', 'DE', 'Klasse 8'),
('de-k9', 'DE', 'Klasse 9'),
('de-k10', 'DE', 'Klasse 10'),
('jhs1', 'GH', 'JHS 1'),
('jhs2', 'GH', 'JHS 2'),
('jhs3', 'GH', 'JHS 3 (BECE)'),
('shs1', 'GH', 'SHS 1'),
('gi-g7', 'GI', 'Grade 7'),
('gi-g8', 'GI', 'Grade 8'),
('gi-g9', 'GI', 'Grade 9'),
('gi-g10', 'GI', 'Grade 10'),
('gr-g7', 'GR', 'Grade 7'),
('gr-g8', 'GR', 'Grade 8'),
('gr-g9', 'GR', 'Grade 9'),
('gr-g10', 'GR', 'Grade 10'),
('gl-g7', 'GL', 'Grade 7'),
('gl-g8', 'GL', 'Grade 8'),
('gl-g9', 'GL', 'Grade 9'),
('gl-g10', 'GL', 'Grade 10'),
('gd-f1', 'GD', 'Form 1'),
('gd-f2', 'GD', 'Form 2'),
('gd-f3', 'GD', 'Form 3'),
('gp-g7', 'GP', 'Grade 7'),
('gp-g8', 'GP', 'Grade 8'),
('gp-g9', 'GP', 'Grade 9'),
('gp-g10', 'GP', 'Grade 10'),
('gu-g7', 'GU', 'Grade 7'),
('gu-g8', 'GU', 'Grade 8'),
('gu-g9', 'GU', 'Grade 9'),
('gu-g10', 'GU', 'Grade 10'),
('gt-g7', 'GT', '7º Grado'),
('gt-g8', 'GT', '8º Grado'),
('gt-g9', 'GT', '9º Grado'),
('gg-g7', 'GG', 'Grade 7'),
('gg-g8', 'GG', 'Grade 8'),
('gg-g9', 'GG', 'Grade 9'),
('gg-g10', 'GG', 'Grade 10'),
('gn-g6', 'GN', '6ème'),
('gn-g5', 'GN', '5ème'),
('gn-g4', 'GN', '4ème'),
('gn-g3', 'GN', '3ème'),
('gw-g7', 'GW', 'Grade 7'),
('gw-g8', 'GW', 'Grade 8'),
('gw-g9', 'GW', 'Grade 9'),
('gw-g10', 'GW', 'Grade 10'),
('gy-f1', 'GY', 'Form 1'),
('gy-f2', 'GY', 'Form 2'),
('gy-f3', 'GY', 'Form 3'),
('ht-g6', 'HT', '6ème'),
('ht-g5', 'HT', '5ème'),
('ht-g4', 'HT', '4ème'),
('ht-g3', 'HT', '3ème'),
('hm-g7', 'HM', 'Grade 7'),
('hm-g8', 'HM', 'Grade 8'),
('hm-g9', 'HM', 'Grade 9'),
('hm-g10', 'HM', 'Grade 10'),
('va-g7', 'VA', 'Grade 7'),
('va-g8', 'VA', 'Grade 8'),
('va-g9', 'VA', 'Grade 9'),
('va-g10', 'VA', 'Grade 10'),
('hn-g7', 'HN', '7º Grado'),
('hn-g8', 'HN', '8º Grado'),
('hn-g9', 'HN', '9º Grado'),
('hk-g7', 'HK', 'Grade 7'),
('hk-g8', 'HK', 'Grade 8'),
('hk-g9', 'HK', 'Grade 9'),
('hk-g10', 'HK', 'Grade 10'),
('hu-g7', 'HU', 'Grade 7'),
('hu-g8', 'HU', 'Grade 8'),
('hu-g9', 'HU', 'Grade 9'),
('hu-g10', 'HU', 'Grade 10'),
('is-g7', 'IS', 'Grade 7'),
('is-g8', 'IS', 'Grade 8'),
('is-g9', 'IS', 'Grade 9'),
('is-g10', 'IS', 'Grade 10'),
('in-c7', 'IN', 'Class 7'),
('in-c8', 'IN', 'Class 8'),
('in-c9', 'IN', 'Class 9'),
('in-c10', 'IN', 'Class 10'),
('id-g7', 'ID', 'Grade 7'),
('id-g8', 'ID', 'Grade 8'),
('id-g9', 'ID', 'Grade 9'),
('id-g10', 'ID', 'Grade 10'),
('ir-g7', 'IR', 'Grade 7'),
('ir-g8', 'IR', 'Grade 8'),
('ir-g9', 'IR', 'Grade 9'),
('ir-g10', 'IR', 'Grade 10'),
('iq-g7', 'IQ', 'Grade 7'),
('iq-g8', 'IQ', 'Grade 8'),
('iq-g9', 'IQ', 'Grade 9'),
('iq-g10', 'IQ', 'Grade 10'),
('ie-g7', 'IE', 'Grade 7'),
('ie-g8', 'IE', 'Grade 8'),
('ie-g9', 'IE', 'Grade 9'),
('ie-g10', 'IE', 'Grade 10'),
('im-g7', 'IM', 'Grade 7'),
('im-g8', 'IM', 'Grade 8'),
('im-g9', 'IM', 'Grade 9'),
('im-g10', 'IM', 'Grade 10'),
('il-g7', 'IL', 'Grade 7'),
('il-g8', 'IL', 'Grade 8'),
('il-g9', 'IL', 'Grade 9'),
('il-g10', 'IL', 'Grade 10'),
('it-g7', 'IT', 'Grade 7'),
('it-g8', 'IT', 'Grade 8'),
('it-g9', 'IT', 'Grade 9'),
('it-g10', 'IT', 'Grade 10'),
('jm-g7', 'JM', 'Grade 7'),
('jm-g8', 'JM', 'Grade 8'),
('jm-g9', 'JM', 'Grade 9'),
('jm-g10', 'JM', 'Grade 10'),
('jp-jh1', 'JP', 'Junior High 1'),
('jp-jh2', 'JP', 'Junior High 2'),
('jp-jh3', 'JP', 'Junior High 3'),
('je-g7', 'JE', 'Grade 7'),
('je-g8', 'JE', 'Grade 8'),
('je-g9', 'JE', 'Grade 9'),
('je-g10', 'JE', 'Grade 10'),
('jo-g7', 'JO', 'Grade 7'),
('jo-g8', 'JO', 'Grade 8'),
('jo-g9', 'JO', 'Grade 9'),
('jo-g10', 'JO', 'Grade 10'),
('kz-g7', 'KZ', 'Grade 7'),
('kz-g8', 'KZ', 'Grade 8'),
('kz-g9', 'KZ', 'Grade 9'),
('kz-g10', 'KZ', 'Grade 10'),
('ke-g7', 'KE', 'Grade 7'),
('ke-g8', 'KE', 'Grade 8'),
('ke-g9', 'KE', 'Grade 9'),
('ke-g10', 'KE', 'Grade 10'),
('ki-g7', 'KI', 'Grade 7'),
('ki-g8', 'KI', 'Grade 8'),
('ki-g9', 'KI', 'Grade 9'),
('ki-g10', 'KI', 'Grade 10'),
('kp-g7', 'KP', 'Grade 7'),
('kp-g8', 'KP', 'Grade 8'),
('kp-g9', 'KP', 'Grade 9'),
('kp-g10', 'KP', 'Grade 10'),
('kr-g7', 'KR', 'Grade 7'),
('kr-g8', 'KR', 'Grade 8'),
('kr-g9', 'KR', 'Grade 9'),
('kr-g10', 'KR', 'Grade 10'),
('kw-g7', 'KW', 'Grade 7'),
('kw-g8', 'KW', 'Grade 8'),
('kw-g9', 'KW', 'Grade 9'),
('kw-g10', 'KW', 'Grade 10'),
('kg-g7', 'KG', 'Grade 7'),
('kg-g8', 'KG', 'Grade 8'),
('kg-g9', 'KG', 'Grade 9'),
('kg-g10', 'KG', 'Grade 10'),
('la-g7', 'LA', 'Grade 7'),
('la-g8', 'LA', 'Grade 8'),
('la-g9', 'LA', 'Grade 9'),
('la-g10', 'LA', 'Grade 10'),
('lv-g7', 'LV', 'Grade 7'),
('lv-g8', 'LV', 'Grade 8'),
('lv-g9', 'LV', 'Grade 9'),
('lv-g10', 'LV', 'Grade 10'),
('lb-g7', 'LB', 'Grade 7'),
('lb-g8', 'LB', 'Grade 8'),
('lb-g9', 'LB', 'Grade 9'),
('lb-g10', 'LB', 'Grade 10'),
('ls-g7', 'LS', 'Grade 7'),
('ls-g8', 'LS', 'Grade 8'),
('ls-g9', 'LS', 'Grade 9'),
('ls-g10', 'LS', 'Grade 10'),
('lr-g7', 'LR', 'Grade 7'),
('lr-g8', 'LR', 'Grade 8'),
('lr-g9', 'LR', 'Grade 9'),
('lr-g10', 'LR', 'Grade 10'),
('ly-g7', 'LY', 'Grade 7'),
('ly-g8', 'LY', 'Grade 8'),
('ly-g9', 'LY', 'Grade 9'),
('ly-g10', 'LY', 'Grade 10'),
('li-g7', 'LI', 'Grade 7'),
('li-g8', 'LI', 'Grade 8'),
('li-g9', 'LI', 'Grade 9'),
('li-g10', 'LI', 'Grade 10'),
('lt-g7', 'LT', 'Grade 7'),
('lt-g8', 'LT', 'Grade 8'),
('lt-g9', 'LT', 'Grade 9'),
('lt-g10', 'LT', 'Grade 10'),
('lu-g7', 'LU', 'Grade 7'),
('lu-g8', 'LU', 'Grade 8'),
('lu-g9', 'LU', 'Grade 9'),
('lu-g10', 'LU', 'Grade 10'),
('mo-g7', 'MO', 'Grade 7'),
('mo-g8', 'MO', 'Grade 8'),
('mo-g9', 'MO', 'Grade 9'),
('mo-g10', 'MO', 'Grade 10'),
('mg-g6', 'MG', '6ème'),
('mg-g5', 'MG', '5ème'),
('mg-g4', 'MG', '4ème'),
('mg-g3', 'MG', '3ème'),
('mw-g7', 'MW', 'Grade 7'),
('mw-g8', 'MW', 'Grade 8'),
('mw-g9', 'MW', 'Grade 9'),
('mw-g10', 'MW', 'Grade 10'),
('my-g7', 'MY', 'Grade 7'),
('my-g8', 'MY', 'Grade 8'),
('my-g9', 'MY', 'Grade 9'),
('my-g10', 'MY', 'Grade 10'),
('mv-g7', 'MV', 'Grade 7'),
('mv-g8', 'MV', 'Grade 8'),
('mv-g9', 'MV', 'Grade 9'),
('mv-g10', 'MV', 'Grade 10'),
('ml-g6', 'ML', '6ème'),
('ml-g5', 'ML', '5ème'),
('ml-g4', 'ML', '4ème'),
('ml-g3', 'ML', '3ème'),
('mt-g7', 'MT', 'Grade 7'),
('mt-g8', 'MT', 'Grade 8'),
('mt-g9', 'MT', 'Grade 9'),
('mt-g10', 'MT', 'Grade 10'),
('mh-g7', 'MH', 'Grade 7'),
('mh-g8', 'MH', 'Grade 8'),
('mh-g9', 'MH', 'Grade 9'),
('mh-g10', 'MH', 'Grade 10'),
('mq-g7', 'MQ', 'Grade 7'),
('mq-g8', 'MQ', 'Grade 8'),
('mq-g9', 'MQ', 'Grade 9'),
('mq-g10', 'MQ', 'Grade 10'),
('mr-g7', 'MR', 'Grade 7'),
('mr-g8', 'MR', 'Grade 8'),
('mr-g9', 'MR', 'Grade 9'),
('mr-g10', 'MR', 'Grade 10'),
('mu-g7', 'MU', 'Grade 7'),
('mu-g8', 'MU', 'Grade 8'),
('mu-g9', 'MU', 'Grade 9'),
('mu-g10', 'MU', 'Grade 10'),
('yt-g7', 'YT', 'Grade 7'),
('yt-g8', 'YT', 'Grade 8'),
('yt-g9', 'YT', 'Grade 9'),
('yt-g10', 'YT', 'Grade 10'),
('mx-1sec', 'MX', '1º Secundaria'),
('mx-2sec', 'MX', '2º Secundaria'),
('mx-3sec', 'MX', '3º Secundaria'),
('fm-g7', 'FM', 'Grade 7'),
('fm-g8', 'FM', 'Grade 8'),
('fm-g9', 'FM', 'Grade 9'),
('fm-g10', 'FM', 'Grade 10'),
('md-g7', 'MD', 'Grade 7'),
('md-g8', 'MD', 'Grade 8'),
('md-g9', 'MD', 'Grade 9'),
('md-g10', 'MD', 'Grade 10'),
('mc-g6', 'MC', '6ème'),
('mc-g5', 'MC', '5ème'),
('mc-g4', 'MC', '4ème'),
('mc-g3', 'MC', '3ème'),
('mn-g7', 'MN', 'Grade 7'),
('mn-g8', 'MN', 'Grade 8'),
('mn-g9', 'MN', 'Grade 9'),
('mn-g10', 'MN', 'Grade 10'),
('me-g7', 'ME', 'Grade 7'),
('me-g8', 'ME', 'Grade 8'),
('me-g9', 'ME', 'Grade 9'),
('me-g10', 'ME', 'Grade 10'),
('ms-g7', 'MS', 'Grade 7'),
('ms-g8', 'MS', 'Grade 8'),
('ms-g9', 'MS', 'Grade 9'),
('ms-g10', 'MS', 'Grade 10'),
('ma-g7', 'MA', 'Grade 7'),
('ma-g8', 'MA', 'Grade 8'),
('ma-g9', 'MA', 'Grade 9'),
('ma-g10', 'MA', 'Grade 10'),
('mz-g7', 'MZ', 'Grade 7'),
('mz-g8', 'MZ', 'Grade 8'),
('mz-g9', 'MZ', 'Grade 9'),
('mz-g10', 'MZ', 'Grade 10'),
('mm-g7', 'MM', 'Grade 7'),
('mm-g8', 'MM', 'Grade 8'),
('mm-g9', 'MM', 'Grade 9'),
('mm-g10', 'MM', 'Grade 10'),
('na-g7', 'NA', 'Grade 7'),
('na-g8', 'NA', 'Grade 8'),
('na-g9', 'NA', 'Grade 9'),
('na-g10', 'NA', 'Grade 10'),
('nr-g7', 'NR', 'Grade 7'),
('nr-g8', 'NR', 'Grade 8'),
('nr-g9', 'NR', 'Grade 9'),
('nr-g10', 'NR', 'Grade 10'),
('np-g7', 'NP', 'Grade 7'),
('np-g8', 'NP', 'Grade 8'),
('np-g9', 'NP', 'Grade 9'),
('np-g10', 'NP', 'Grade 10'),
('nl-g7', 'NL', 'Grade 7'),
('nl-g8', 'NL', 'Grade 8'),
('nl-g9', 'NL', 'Grade 9'),
('nl-g10', 'NL', 'Grade 10'),
('nc-g7', 'NC', 'Grade 7'),
('nc-g8', 'NC', 'Grade 8'),
('nc-g9', 'NC', 'Grade 9'),
('nc-g10', 'NC', 'Grade 10'),
('nz-y9', 'NZ', 'Year 9'),
('nz-y10', 'NZ', 'Year 10'),
('nz-y11', 'NZ', 'Year 11'),
('ni-g7', 'NI', '7º Grado'),
('ni-g8', 'NI', '8º Grado'),
('ni-g9', 'NI', '9º Grado'),
('ne-g6', 'NE', '6ème'),
('ne-g5', 'NE', '5ème'),
('ne-g4', 'NE', '4ème'),
('ne-g3', 'NE', '3ème'),
('jss2', 'NG', 'JSS 2'),
('jss3', 'NG', 'JSS 3'),
('ss1', 'NG', 'SS 1'),
('nu-g7', 'NU', 'Grade 7'),
('nu-g8', 'NU', 'Grade 8'),
('nu-g9', 'NU', 'Grade 9'),
('nu-g10', 'NU', 'Grade 10'),
('nf-g7', 'NF', 'Grade 7'),
('nf-g8', 'NF', 'Grade 8'),
('nf-g9', 'NF', 'Grade 9'),
('nf-g10', 'NF', 'Grade 10'),
('mp-g7', 'MP', 'Grade 7'),
('mp-g8', 'MP', 'Grade 8'),
('mp-g9', 'MP', 'Grade 9'),
('mp-g10', 'MP', 'Grade 10'),
('no-g7', 'NO', 'Grade 7'),
('no-g8', 'NO', 'Grade 8'),
('no-g9', 'NO', 'Grade 9'),
('no-g10', 'NO', 'Grade 10'),
('om-g7', 'OM', 'Grade 7'),
('om-g8', 'OM', 'Grade 8'),
('om-g9', 'OM', 'Grade 9'),
('om-g10', 'OM', 'Grade 10'),
('pk-c7', 'PK', 'Class 7'),
('pk-c8', 'PK', 'Class 8'),
('pk-c9', 'PK', 'Class 9'),
('pk-c10', 'PK', 'Class 10'),
('pw-g7', 'PW', 'Grade 7'),
('pw-g8', 'PW', 'Grade 8'),
('pw-g9', 'PW', 'Grade 9'),
('pw-g10', 'PW', 'Grade 10'),
('ps-g7', 'PS', 'Grade 7'),
('ps-g8', 'PS', 'Grade 8'),
('ps-g9', 'PS', 'Grade 9'),
('ps-g10', 'PS', 'Grade 10'),
('pa-g7', 'PA', '7º Grado'),
('pa-g8', 'PA', '8º Grado'),
('pa-g9', 'PA', '9º Grado'),
('pg-g7', 'PG', 'Grade 7'),
('pg-g8', 'PG', 'Grade 8'),
('pg-g9', 'PG', 'Grade 9'),
('pg-g10', 'PG', 'Grade 10'),
('py-g7', 'PY', '7º Grado'),
('py-g8', 'PY', '8º Grado'),
('py-g9', 'PY', '9º Grado'),
('pe-g7', 'PE', '7º Grado'),
('pe-g8', 'PE', '8º Grado'),
('pe-g9', 'PE', '9º Grado'),
('ph-g7', 'PH', 'Grade 7'),
('ph-g8', 'PH', 'Grade 8'),
('ph-g9', 'PH', 'Grade 9'),
('ph-g10', 'PH', 'Grade 10'),
('pn-g7', 'PN', 'Grade 7'),
('pn-g8', 'PN', 'Grade 8'),
('pn-g9', 'PN', 'Grade 9'),
('pn-g10', 'PN', 'Grade 10'),
('pl-g7', 'PL', 'Grade 7'),
('pl-g8', 'PL', 'Grade 8'),
('pl-g9', 'PL', 'Grade 9'),
('pl-g10', 'PL', 'Grade 10'),
('pt-g7', 'PT', 'Grade 7'),
('pt-g8', 'PT', 'Grade 8'),
('pt-g9', 'PT', 'Grade 9'),
('pt-g10', 'PT', 'Grade 10'),
('pr-g7', 'PR', 'Grade 7'),
('pr-g8', 'PR', 'Grade 8'),
('pr-g9', 'PR', 'Grade 9'),
('pr-g10', 'PR', 'Grade 10'),
('qa-g7', 'QA', 'Grade 7'),
('qa-g8', 'QA', 'Grade 8'),
('qa-g9', 'QA', 'Grade 9'),
('qa-g10', 'QA', 'Grade 10'),
('re-g7', 'RE', 'Grade 7'),
('re-g8', 'RE', 'Grade 8'),
('re-g9', 'RE', 'Grade 9'),
('re-g10', 'RE', 'Grade 10'),
('ro-g7', 'RO', 'Grade 7'),
('ro-g8', 'RO', 'Grade 8'),
('ro-g9', 'RO', 'Grade 9'),
('ro-g10', 'RO', 'Grade 10'),
('ru-g7', 'RU', 'Grade 7'),
('ru-g8', 'RU', 'Grade 8'),
('ru-g9', 'RU', 'Grade 9'),
('ru-g10', 'RU', 'Grade 10'),
('rw-g6', 'RW', '6ème'),
('rw-g5', 'RW', '5ème'),
('rw-g4', 'RW', '4ème'),
('rw-g3', 'RW', '3ème'),
('bl-g7', 'BL', 'Grade 7'),
('bl-g8', 'BL', 'Grade 8'),
('bl-g9', 'BL', 'Grade 9'),
('bl-g10', 'BL', 'Grade 10'),
('sh-g7', 'SH', 'Grade 7'),
('sh-g8', 'SH', 'Grade 8'),
('sh-g9', 'SH', 'Grade 9'),
('sh-g10', 'SH', 'Grade 10'),
('kn-f1', 'KN', 'Form 1'),
('kn-f2', 'KN', 'Form 2'),
('kn-f3', 'KN', 'Form 3'),
('lc-f1', 'LC', 'Form 1'),
('lc-f2', 'LC', 'Form 2'),
('lc-f3', 'LC', 'Form 3'),
('mf-g7', 'MF', 'Grade 7'),
('mf-g8', 'MF', 'Grade 8'),
('mf-g9', 'MF', 'Grade 9'),
('mf-g10', 'MF', 'Grade 10'),
('pm-g7', 'PM', 'Grade 7'),
('pm-g8', 'PM', 'Grade 8'),
('pm-g9', 'PM', 'Grade 9'),
('pm-g10', 'PM', 'Grade 10'),
('vc-f1', 'VC', 'Form 1'),
('vc-f2', 'VC', 'Form 2'),
('vc-f3', 'VC', 'Form 3'),
('ws-g7', 'WS', 'Grade 7'),
('ws-g8', 'WS', 'Grade 8'),
('ws-g9', 'WS', 'Grade 9'),
('ws-g10', 'WS', 'Grade 10'),
('sm-g7', 'SM', 'Grade 7'),
('sm-g8', 'SM', 'Grade 8'),
('sm-g9', 'SM', 'Grade 9'),
('sm-g10', 'SM', 'Grade 10'),
('st-g7', 'ST', 'Grade 7'),
('st-g8', 'ST', 'Grade 8'),
('st-g9', 'ST', 'Grade 9'),
('st-g10', 'ST', 'Grade 10'),
('sa-g7', 'SA', 'Grade 7'),
('sa-g8', 'SA', 'Grade 8'),
('sa-g9', 'SA', 'Grade 9'),
('sa-g10', 'SA', 'Grade 10'),
('sn-g6', 'SN', '6ème'),
('sn-g5', 'SN', '5ème'),
('sn-g4', 'SN', '4ème'),
('sn-g3', 'SN', '3ème'),
('rs-g7', 'RS', 'Grade 7'),
('rs-g8', 'RS', 'Grade 8'),
('rs-g9', 'RS', 'Grade 9'),
('rs-g10', 'RS', 'Grade 10'),
('sc-g7', 'SC', 'Grade 7'),
('sc-g8', 'SC', 'Grade 8'),
('sc-g9', 'SC', 'Grade 9'),
('sc-g10', 'SC', 'Grade 10'),
('sl-g7', 'SL', 'Grade 7'),
('sl-g8', 'SL', 'Grade 8'),
('sl-g9', 'SL', 'Grade 9'),
('sl-g10', 'SL', 'Grade 10'),
('sg-s1', 'SG', 'Secondary 1'),
('sg-s2', 'SG', 'Secondary 2'),
('sg-s3', 'SG', 'Secondary 3'),
('sg-s4', 'SG', 'Secondary 4'),
('sx-g7', 'SX', 'Grade 7'),
('sx-g8', 'SX', 'Grade 8'),
('sx-g9', 'SX', 'Grade 9'),
('sx-g10', 'SX', 'Grade 10'),
('sk-g7', 'SK', 'Grade 7'),
('sk-g8', 'SK', 'Grade 8'),
('sk-g9', 'SK', 'Grade 9'),
('sk-g10', 'SK', 'Grade 10'),
('si-g7', 'SI', 'Grade 7'),
('si-g8', 'SI', 'Grade 8'),
('si-g9', 'SI', 'Grade 9'),
('si-g10', 'SI', 'Grade 10'),
('sb-g7', 'SB', 'Grade 7'),
('sb-g8', 'SB', 'Grade 8'),
('sb-g9', 'SB', 'Grade 9'),
('sb-g10', 'SB', 'Grade 10'),
('so-g7', 'SO', 'Grade 7'),
('so-g8', 'SO', 'Grade 8'),
('so-g9', 'SO', 'Grade 9'),
('so-g10', 'SO', 'Grade 10'),
('za-g7', 'ZA', 'Grade 7'),
('za-g8', 'ZA', 'Grade 8'),
('za-g9', 'ZA', 'Grade 9'),
('za-g10', 'ZA', 'Grade 10'),
('gs-g7', 'GS', 'Grade 7'),
('gs-g8', 'GS', 'Grade 8'),
('gs-g9', 'GS', 'Grade 9'),
('gs-g10', 'GS', 'Grade 10'),
('ss-g7', 'SS', 'Grade 7'),
('ss-g8', 'SS', 'Grade 8'),
('ss-g9', 'SS', 'Grade 9'),
('ss-g10', 'SS', 'Grade 10'),
('es-1eso', 'ES', '1º ESO'),
('es-2eso', 'ES', '2º ESO'),
('es-3eso', 'ES', '3º ESO'),
('es-4eso', 'ES', '4º ESO'),
('lk-g7', 'LK', 'Grade 7'),
('lk-g8', 'LK', 'Grade 8'),
('lk-g9', 'LK', 'Grade 9'),
('lk-g10', 'LK', 'Grade 10'),
('sd-g7', 'SD', 'Grade 7'),
('sd-g8', 'SD', 'Grade 8'),
('sd-g9', 'SD', 'Grade 9'),
('sd-g10', 'SD', 'Grade 10'),
('sr-g7', 'SR', 'Grade 7'),
('sr-g8', 'SR', 'Grade 8'),
('sr-g9', 'SR', 'Grade 9'),
('sr-g10', 'SR', 'Grade 10'),
('sj-g7', 'SJ', 'Grade 7'),
('sj-g8', 'SJ', 'Grade 8'),
('sj-g9', 'SJ', 'Grade 9'),
('sj-g10', 'SJ', 'Grade 10'),
('se-g7', 'SE', 'Grade 7'),
('se-g8', 'SE', 'Grade 8'),
('se-g9', 'SE', 'Grade 9'),
('se-g10', 'SE', 'Grade 10'),
('ch-g7', 'CH', 'Grade 7'),
('ch-g8', 'CH', 'Grade 8'),
('ch-g9', 'CH', 'Grade 9'),
('ch-g10', 'CH', 'Grade 10'),
('sy-g7', 'SY', 'Grade 7'),
('sy-g8', 'SY', 'Grade 8'),
('sy-g9', 'SY', 'Grade 9'),
('sy-g10', 'SY', 'Grade 10'),
('tw-g7', 'TW', 'Grade 7'),
('tw-g8', 'TW', 'Grade 8'),
('tw-g9', 'TW', 'Grade 9'),
('tw-g10', 'TW', 'Grade 10'),
('tj-g7', 'TJ', 'Grade 7'),
('tj-g8', 'TJ', 'Grade 8'),
('tj-g9', 'TJ', 'Grade 9'),
('tj-g10', 'TJ', 'Grade 10'),
('tz-g7', 'TZ', 'Grade 7'),
('tz-g8', 'TZ', 'Grade 8'),
('tz-g9', 'TZ', 'Grade 9'),
('tz-g10', 'TZ', 'Grade 10'),
('th-g7', 'TH', 'Grade 7'),
('th-g8', 'TH', 'Grade 8'),
('th-g9', 'TH', 'Grade 9'),
('th-g10', 'TH', 'Grade 10'),
('tl-g7', 'TL', 'Grade 7'),
('tl-g8', 'TL', 'Grade 8'),
('tl-g9', 'TL', 'Grade 9'),
('tl-g10', 'TL', 'Grade 10'),
('tg-g6', 'TG', '6ème'),
('tg-g5', 'TG', '5ème'),
('tg-g4', 'TG', '4ème'),
('tg-g3', 'TG', '3ème'),
('tk-g7', 'TK', 'Grade 7'),
('tk-g8', 'TK', 'Grade 8'),
('tk-g9', 'TK', 'Grade 9'),
('tk-g10', 'TK', 'Grade 10'),
('to-g7', 'TO', 'Grade 7'),
('to-g8', 'TO', 'Grade 8'),
('to-g9', 'TO', 'Grade 9'),
('to-g10', 'TO', 'Grade 10'),
('tt-f1', 'TT', 'Form 1'),
('tt-f2', 'TT', 'Form 2'),
('tt-f3', 'TT', 'Form 3'),
('tn-g6', 'TN', '6ème'),
('tn-g5', 'TN', '5ème'),
('tn-g4', 'TN', '4ème'),
('tn-g3', 'TN', '3ème'),
('tr-g7', 'TR', 'Grade 7'),
('tr-g8', 'TR', 'Grade 8'),
('tr-g9', 'TR', 'Grade 9'),
('tr-g10', 'TR', 'Grade 10'),
('tm-g7', 'TM', 'Grade 7'),
('tm-g8', 'TM', 'Grade 8'),
('tm-g9', 'TM', 'Grade 9'),
('tm-g10', 'TM', 'Grade 10'),
('tc-g7', 'TC', 'Grade 7'),
('tc-g8', 'TC', 'Grade 8'),
('tc-g9', 'TC', 'Grade 9'),
('tc-g10', 'TC', 'Grade 10'),
('tv-g7', 'TV', 'Grade 7'),
('tv-g8', 'TV', 'Grade 8'),
('tv-g9', 'TV', 'Grade 9'),
('tv-g10', 'TV', 'Grade 10'),
('ug-g7', 'UG', 'Grade 7'),
('ug-g8', 'UG', 'Grade 8'),
('ug-g9', 'UG', 'Grade 9'),
('ug-g10', 'UG', 'Grade 10'),
('ua-g7', 'UA', 'Grade 7'),
('ua-g8', 'UA', 'Grade 8'),
('ua-g9', 'UA', 'Grade 9'),
('ua-g10', 'UA', 'Grade 10'),
('ae-g7', 'AE', 'Grade 7'),
('ae-g8', 'AE', 'Grade 8'),
('ae-g9', 'AE', 'Grade 9'),
('ae-g10', 'AE', 'Grade 10'),
('y8', 'GB', 'Year 8'),
('y9', 'GB', 'Year 9'),
('y10', 'GB', 'Year 10 (GCSE)'),
('um-g7', 'UM', 'Grade 7'),
('um-g8', 'UM', 'Grade 8'),
('um-g9', 'UM', 'Grade 9'),
('um-g10', 'UM', 'Grade 10'),
('g6', 'US', 'Grade 6'),
('g7', 'US', 'Grade 7'),
('g8', 'US', 'Grade 8'),
('g9', 'US', 'Grade 9 (Algebra I)'),
('uy-g7', 'UY', '7º Grado'),
('uy-g8', 'UY', '8º Grado'),
('uy-g9', 'UY', '9º Grado'),
('uz-g7', 'UZ', 'Grade 7'),
('uz-g8', 'UZ', 'Grade 8'),
('uz-g9', 'UZ', 'Grade 9'),
('uz-g10', 'UZ', 'Grade 10'),
('vu-g6', 'VU', '6ème'),
('vu-g5', 'VU', '5ème'),
('vu-g4', 'VU', '4ème'),
('vu-g3', 'VU', '3ème'),
('ve-g7', 'VE', '7º Grado'),
('ve-g8', 'VE', '8º Grado'),
('ve-g9', 'VE', '9º Grado'),
('vn-g7', 'VN', 'Grade 7'),
('vn-g8', 'VN', 'Grade 8'),
('vn-g9', 'VN', 'Grade 9'),
('vn-g10', 'VN', 'Grade 10'),
('vg-g7', 'VG', 'Grade 7'),
('vg-g8', 'VG', 'Grade 8'),
('vg-g9', 'VG', 'Grade 9'),
('vg-g10', 'VG', 'Grade 10'),
('vi-g7', 'VI', 'Grade 7'),
('vi-g8', 'VI', 'Grade 8'),
('vi-g9', 'VI', 'Grade 9'),
('vi-g10', 'VI', 'Grade 10'),
('wf-g7', 'WF', 'Grade 7'),
('wf-g8', 'WF', 'Grade 8'),
('wf-g9', 'WF', 'Grade 9'),
('wf-g10', 'WF', 'Grade 10'),
('eh-g7', 'EH', 'Grade 7'),
('eh-g8', 'EH', 'Grade 8'),
('eh-g9', 'EH', 'Grade 9'),
('eh-g10', 'EH', 'Grade 10'),
('ye-g7', 'YE', 'Grade 7'),
('ye-g8', 'YE', 'Grade 8'),
('ye-g9', 'YE', 'Grade 9'),
('ye-g10', 'YE', 'Grade 10'),
('zm-g7', 'ZM', 'Grade 7'),
('zm-g8', 'ZM', 'Grade 8'),
('zm-g9', 'ZM', 'Grade 9'),
('zm-g10', 'ZM', 'Grade 10'),
('zw-g7', 'ZW', 'Grade 7'),
('zw-g8', 'ZW', 'Grade 8'),
('zw-g9', 'ZW', 'Grade 9'),
('zw-g10', 'ZW', 'Grade 10')
ON CONFLICT (id) DO UPDATE SET
  country_code = EXCLUDED.country_code,
  label = EXCLUDED.label;
